### ISSUE TITLE
How to use RegisterWidgetPermissions

### ISSUE THREAD

**Issue by dmueller-sa** [KenticoDevTrev/XperienceCommunity.WidgetFilter#1]
Hello. The usage example doesn't appear to include any specifics on how to use RegisterWidgetPermissions. Can you please provide an example of this? I have a widget registration that looks like this:

[assembly: RegisterWidget("Namespace.InfographicWidget", typeof(InfographicWidget), "Infographic Widget", typeof(InfographicWidgetProperties), IconClass = "icon-heartshake")]

What steps are needed to require that any user of this widget has a global administrator role?

Thank you!

**Comment by KenticoDevTrev** [comment]
It is in the readme, but wasn't as easy to spot.  Updated.

Just add the `[assembly: RegisterWidgetPermissions()]` attribute and add in the fields to the constructor.
